project:
  type: website
  output-dir: docs
  

website:
  title: "UNICEF_Report_on_C-Section_Births"
  navbar:
    left:
      - href: index_fixed.html
        text: Home

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    embed-resources: true
    code-fold: true

editor: visual
