project:
  type: website
  

website:
  title: "UNICEF_Report_on_C-Section_Births"
  navbar:
    left:
      - href: index_fixed.qmd
        text: Home

  
  page-navigation: true
  site-url: https://deric301.github.io/unicef-quarto-dericbenpaul/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    embed-resources: true
    code-fold: true

editor: visual
